services:
  - type: web
    name: dingerstats-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api:app"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
